name: Java CI with Maven

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master","develop" ]

permissions:
  contents: read
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build Image Docker
      run: docker build -t apiola:latest .

    #- name: Install AWS CLI
    #  run: |
    #    sudo apt-get update
    #    sudo apt-get install -y awscli  

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: us-east-1

    - name: Check Repository Exists
      id: check_repo
      run: |
        aws ecr describe-repositories --repository-names apiola --region us-east-1 || echo "Repository does not exist"

    - name: Create a Repository
      if: steps.check_repo.outputs.result == true ||  steps.check_repo.outputs.result == 'Repository does not exist'
      run: |
        aws ecr --region us-east-1 create-repository --repository-name apiola

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

    - name: Tag Docker Image
      run: |
        docker tag apiola:latest ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.us-east-1.amazonaws.com/apiola:apiolav2

    - name: Docker push
      run: |
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/apiola:apiolav2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: |
        terraform plan \
          -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY }}" \
          -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          -var="aws_region=us-east-1"

    #- name: Terraform Apply
    #  if: github.ref == 'refs/heads/develop'
    #  run: |
    #    terraform apply \
    #      -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY }}" \
    #      -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
    #      -var="aws_region=us-east-1" \
    #      -auto-approve